// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi2nU1T0ot_n5TX68Ifqs5Nf4zpbVJwzY',
    appId: '1:145052017661:android:843b341b14e265be6f2f94',
    messagingSenderId: '145052017661',
    projectId: 'flutter-test-15613',
    storageBucket: 'flutter-test-15613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0wFXGF1cnbu9GDQhScv9E7hrmlb_Jf5U',
    appId: '1:145052017661:ios:a16ba373a21fb5656f2f94',
    messagingSenderId: '145052017661',
    projectId: 'flutter-test-15613',
    storageBucket: 'flutter-test-15613.appspot.com',
    iosClientId: '145052017661-eq3mmjckh1dfrvsqodh38v9868onobpo.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTestFlutter',
  );
}
